### PR TITLE
Add StatefulView.stencil

### PR DESCRIPTION
**Pull request by zenangst**
This PR adds the initial implementation of a generated stateful view controller.

### CODE REVIEW

**Review by vadymmarkov — APPROVED** [review]
Looks great 😎

**Review by sindrenm — APPROVED** [review]
🎉 🌮 🐱

**Comment by zenangst** [comment]
@vadymmarkov @sindrenm pushed some updates based on the feedback that you awesome peoples provided. Thanks guys, loads of ❤️ !

**Comment by zenangst** [comment]
Merging this sucker now.
Next step would be to generating a view controller factory, I think that could end up pretty great.
#childishlyexcited

**Pull request merged**
